### PR TITLE
Add example using seed param to get consistent outputs

### PR DESCRIPTION
**Pull request by mrkiura**
Updates the examples directory with an example that demonstrates how to reprodduce similar outputs.

### CODE REVIEW

**Review by furqanalishah — COMMENTED** [review]
Thanks lgtm

**Review by furqanalishah — APPROVED** [review]

**Comment by mrkiura** [comment]
I appreciate you taking a look.

**Comment by mrkiura** [comment]
You are right. The `temperature` here should be zero. I observed little variance between 0 and 0.1.

**Review by fujitatomoya — APPROVED** [review]
lgtm, i think this is a good example.

**Comment by ParthSareen** [comment]
Hey @mrkiura, we're trying to keep our examples relatively basic and some of this information will be in the Ollama API spec. Happy to reconsider if you leave a comment on the new examples PR: https://github.com/ollama/ollama-python/pull/329

**Pull request closed without merging**
